name: food
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  flutter_svg: ^0.22.0 # help us to use SVG in our app
  
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.0.6
  after_layout: ^1.1.0
  introduction_screen: ^2.1.0

  provider: ^5.0.0 # for State management
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.1
  google_sign_in: ^5.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/products/
    - assets/text/
    - assets/recipe/
    - assets/catalogue/
  
  fonts:
    - family: HeliosAntique
      fonts:
        - asset: assets/fonts/HeliosAntique.ttf
    - family: Krub
      fonts:
        - asset: assets/fonts/Krub_R.ttf
        - asset: assets/fonts/Krub_L.ttf   
    - family: MyIcons
      fonts:
        - asset: assets/icons/MyIcons.ttf
